### Creating Arrays form Scratch

In [12]:
import numpy as np

In [13]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# Create a 3x3 floating point array filled with 1s
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# Create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [16]:
# Create an array filled with linear sequence
# Starting a 0, ending at 20, stepping by 2
# (this is similar to built-in range() function)
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
# Create an array of five values evenly spaced between o and 1
np.linspace(0,1,5) 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.39671151, 0.52971788, 0.1609784 ],
       [0.02954734, 0.49096025, 0.28140501],
       [0.35102776, 0.72889274, 0.14240515]])

In [19]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3,3))

array([[ 0.26719962, -1.49742708,  1.4211603 ],
       [ 0.95853229,  0.01030378,  0.55634166],
       [-0.58368616,  0.38551191,  0.05676693]])

In [20]:
# Create a 3x3 array of random integers in the interval [0,10]
np.random.randint(0, 10, (3,3))

array([[6, 7, 5],
       [1, 3, 0],
       [2, 5, 7]])

In [21]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location.
np.empty(3)

array([1., 1., 1.])

Wait for next Notebook. Stay connected, Stay tuned!